In [3]:
# 1. Create a numpy array of size 2 x 2
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
#2. Create a random numpy array of size 3 x 4
b = np.random.random((3,4))
print(b)

[[0.70678198 0.36127186 0.59688905 0.60934791]
 [0.40125301 0.4200015  0.14460877 0.81641139]
 [0.46289076 0.27496884 0.76878153 0.05246845]]


In [12]:
#3. Create a numpy array of ones and a numpy array of zeroes
one = np.ones((2,2))
zero = np.zeros((3,3))
print(one)
print()
print(zero)

[[1. 1.]
 [1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#4. Create a random numpy array of size 6x3 and transpose it
c = np.random.random((6,3))
print(c)
print()
c_transpose = c.T
print(c_transpose)

[[0.16355615 0.30451408 0.65815484]
 [0.89007572 0.94086089 0.4646023 ]
 [0.40347644 0.31559628 0.61241572]
 [0.42401409 0.32541526 0.20246118]
 [0.61382298 0.50366372 0.04102243]
 [0.98017691 0.99532461 0.79809768]]

[[0.16355615 0.89007572 0.40347644 0.42401409 0.61382298 0.98017691]
 [0.30451408 0.94086089 0.31559628 0.32541526 0.50366372 0.99532461]
 [0.65815484 0.4646023  0.61241572 0.20246118 0.04102243 0.79809768]]


In [13]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
d = np.random.random((2,3))
e = np.random.random((3,4))
print(d)
print()
print(e)
print()
dot_product = np.dot(d,e)
print(dot_product)


[[0.62571594 0.99094266 0.98746845]
 [0.59894772 0.77332022 0.30415099]]

[[0.64791809 0.88802664 0.25666482 0.16694352]
 [0.57239347 0.86502291 0.41621973 0.56746236]
 [0.52415233 0.62827485 0.74834534 0.77762454]]

[[1.49020568 2.03324212 1.31201656 1.43466158]
 [0.99013396 1.39191166 0.70320992 0.77533584]]
